version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - dist
            - package.json
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

      - run: yarn test:tap

      - run:
          name: Prepare DEPLOY_VERSION
          command: |
            (DEPLOY_VERSION="$(date +%Y%m%d%H%M)-${CIRCLE_BUILD_NUM}" ; \
            echo ${DEPLOY_VERSION} >.deploy_version ; \
            echo "export DEPLOY_VERSION=${DEPLOY_VERSION}" >> $BASH_ENV ; \
            echo "DEPLOY_VERSION=${DEPLOY_VERSION}")

      - run:
          name: Prepare prod env file
          command: |
            echo "DEPLOY_VERSION is: ${DEPLOY_VERSION}"
            echo "" > .prod.env
            echo "BASE=/widget/${DEPLOY_VERSION}/" >> .prod.env
            echo "export BASE=/widget/${DEPLOY_VERSION}/" >> $BASH_ENV

      - run: yarn generate

      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
            - .deploy_version

  deploy:
    docker:
      - image: atlassian/pipelines-awscli:1.16.185
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to S3
          command: (DEPLOY_VERSION=$(cat ~/repo/.deploy_version) ; aws s3 sync ~/repo/dist s3://${SQUAD_BUCKET}/widget/${DEPLOY_VERSION} )
      - run:
          name: Prepare Index Redirection
          command: (DEPLOY_VERSION=$(cat ~/repo/.deploy_version) ; echo "<html><head><meta http-equiv=\"refresh\" content=\"0;URL=${DEPLOY_VERSION}/\"/></head></html>" > /tmp/index.html )
      - run:
          name: Upload index
          command: aws s3 cp /tmp/index.html s3://${SQUAD_BUCKET}/widget/index.html
      - run:
          name: Invalidate CloudFront cache
          command: aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/widget/" "/widget/index.html"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
