version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - dist
            - package.json
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 

      - run: yarn test

      - run:
          name: Prepare prod env file
          command: echo "WS_LINK=${WS_LINK}" > .prod.env

      - run: yarn build
      
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/repo
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
          
      - attach_workspace:
          at: ~/repo

      - run:
          name: Deploy to S3
          command: aws s3 sync ~/repo/dist s3://squad-widget/widget/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

